apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://provectus.github.io/kafka-ui-charts
    chart: kafka-ui/kafka-ui
    targetRevision: 0.7.6
    # helm:
    #   values: 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true